### ISSUE TITLE
Request for License Change to GPLv2

### ISSUE THREAD

**Issue by harshu4** [Openmesh-Network/nft-authorise#2]
**Request:**
We kindly request all contributors to respond to this issue with one of the following:
- **ack**: I approve the license change to GPLv2.
- **nack**: I do not approve the license change to GPLv2.

**Response Deadline:**
Please respond by 14/07/2024. If no response is received by then, it will be assumed that you approve ("ack") of the license change.

Thank you for your attention to this matter.

cc: @harrys522 @harshu4

**Comment by harshu4** [comment]
Ack

**Comment by harrys522** [comment]
Acknowledged, I agree with GPL for this library, apologies for the delay.

**Comment by dowdt** [comment]
As all contributors acknowledged. Adding the license.
![image](https://github.com/user-attachments/assets/64782255-cc8a-4f75-a42b-d6fa1fa9d4ec)
